apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: laravel-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "jobs", "cronjobs", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]




# RBAC ржорж╛ржирзЗ ЁЯСЙ Role-Based Access Control
# ржПржЯрж╛ Kubernetes-ржПрж░ ржПржХржЯрж╛ permission management system тАФ ржпрзЗржЯрж╛ ржирж┐рж░рзНржзрж╛рж░ржг ржХрж░рзЗ ржХрзЗ ржХрзА ржХрж░рждрзЗ ржкрж╛рж░ржмрзЗ, ржХрзЛржи resource-ржП access ржкрж╛ржмрзЗ, ржЖрж░ ржХрзЛржиржЯрж╛рзЯ ржкрж╛ржмрзЗ ржирж╛ ЁЯФР
# ЁЯза рж╕рж╣ржЬржнрж╛ржмрзЗ ржмрж▓рж▓рзЗ:
# Kubernetes-ржП ржЕржирзЗржХ resource ржерж╛ржХрзЗ тАФ ржпрзЗржоржи Pod, Deployment, Secret, ConfigMap ржЗрждрзНржпрж╛ржжрж┐ред
# ржПржЦржи ржзрж░, рждрзБржЗ ржЪрж╛ржЗржЫрж┐рж╕:
# ржПржХржЬржи user ржпрзЗржи рж╢рзБржзрзБ Pod ржжрзЗржЦрждрзЗ ржкрж╛рж░рзЗ ЁЯзР
# ржЖрж░рзЗржХржЬржи ржпрзЗржи Pod delete ржУ ржХрж░рждрзЗ ржкрж╛рж░рзЗ ЁЯТг
# ржПржЗ ржЖрж▓рж╛ржжрж╛ ржЖрж▓рж╛ржжрж╛ permission assign ржХрж░рждрзЗржЗ рж▓рж╛ржЧрзЗ RBACред


# ЁЯФ╣ apiGroups: [""]
# ржПржЦрж╛ржирзЗ ржлрж╛ржБржХрж╛ string ("") ржорж╛ржирзЗ рж╣рж▓рзЛ core API group тАФ
# ржпрзЗржоржи pods, services, configmaps ржЗрждрзНржпрж╛ржжрж┐ред
# (ржпржжрж┐ apps group рж▓рж╛ржЧржд, рждрж╛рж╣рж▓рзЗ рж╣рждрзЛ apiGroups: ["apps"] тАФ ржЙржжрж╛рж╣рж░ржг: deployments, replicasetsред)

# ЁЯФ╣ resources
# ржПржЧрзБрж▓рзЛ рж╣рж▓рзЛ ржХрзЛржи resource-ржПрж░ ржЙржкрж░ permission ржжрзЗржУрзЯрж╛ рж╣ржЪрзНржЫрзЗ:
# pods тЖТ Pod ржЧрзБрж▓рзЛ manage ржХрж░рждрзЗ ржкрж╛рж░ржмрзЗ
# jobs тЖТ Job resource рждрзИрж░рж┐/ржбрж┐рж▓рж┐ржЯ ржХрж░рждрзЗ ржкрж╛рж░ржмрзЗ
# cronjobs тЖТ CronJob resource handle ржХрж░рждрзЗ ржкрж╛рж░ржмрзЗ
# pods/log тЖТ Pod-ржПрж░ log ржжрзЗржЦрждрзЗ ржкрж╛рж░ржмрзЗ

# ЁЯФ╣ verbs
# ржПржЦрж╛ржирзЗ ржирж┐рж░рзНржжрж┐рж╖рзНржЯ action ржмрж╛ permission ржжрзЗржУрзЯрж╛ рж╣рзЯрзЗржЫрзЗ:
# verb	ржорж╛ржирзЗ
# get	ржПржХржЯрж╛ resource ржПрж░ details ржжрзЗржЦрж╛
# list	рж╕ржм resource ржПрж░ рждрж╛рж▓рж┐ржХрж╛ ржжрзЗржЦрж╛
# watch	resource change рж╣рж▓рзЗ observe ржХрж░рж╛
# create	ржирждрзБржи resource рждрзИрж░рж┐ ржХрж░рж╛
# delete	resource ржбрж┐рж▓рж┐ржЯ ржХрж░рж╛