apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: agrobd-app
type: Opaque
stringData:
  root_password: rootpassword123
  username: laravel
  password: laravelpass123
  database: laravel_db
