# NetworkPolicy ржарж┐ржХ ржХрж░рзЗ ржжрзЗрзЯ ржХрзЛржи pod ржХрж╛рж░ рж╕рж╛ржерзЗ ржХржерж╛ ржмрж▓рждрзЗ ржкрж╛рж░ржмрзЗ, ржЖрж░ ржХрж╛рж░ рж╕рж╛ржерзЗ ржкрж╛рж░ржмрзЗ ржирж╛ред
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-app-traffic                        # Name of the NetworkPolicy
spec:
  podSelector:
    matchLabels:
      app: agrobd-laravel-app                    # Apply policy to pods with this label
  policyTypes:
    - Ingress                                    # Controls incoming traffic to selected pods
  ingress:
    - from:                                      # Define which pods are allowed to connect
        - podSelector:
            matchLabels:
              app: mysql                         # Allow traffic from pods labeled 'mysql'
        - podSelector:
            matchLabels:
              app: redis                         # Allow traffic from pods labeled 'redis'
      ports:                                     # Specify allowed ports and protocols
        - protocol: TCP
          port: 3306                             # Allow MySQL traffic (port 3306)
        - protocol: TCP
          port: 6379                             # Allow Redis traffic (port 6379)



# ЁЯФН ржПржЗ YAML-ржПрж░ ржХрж╛ржЬ:
# ржПржЗ ржкрж▓рж┐рж╕рж┐-рждрзЗ ржмрж▓рж╛ ржЖржЫрзЗ тАФ
# app: agrobd-laravel-app рж▓рзЗржмрзЗрж▓-ржУрзЯрж╛рж▓рж╛ pod-ржЧрзБрж▓рзЛ рж╢рзБржзрзБ ржирж┐ржЪрзЗрж░ pod-ржЧрзБрж▓рзЛрж░ ржерзЗржХрзЗ ржЯрзНрж░рж╛ржлрж┐ржХ ржирж┐рждрзЗ ржкрж╛рж░ржмрзЗ тмЗя╕П
# app: mysql
# app: redis
# ржПржмржВ, рж╕рзЗржЗ ржЯрзНрж░рж╛ржлрж┐ржХ ржХрзЗржмрж▓ ржирж┐ржЪрзЗрж░ ржкрзЛрж░рзНржЯржЧрзБрж▓рзЛ ржжрж┐рзЯрзЗ ржЖрж╕рждрзЗ ржкрж╛рж░ржмрзЗ:
# TCP 3306 тЖТ (MySQL ржПрж░ ржбрж╛ржЯрж╛ржмрзЗржЬ ржХрж╛ржирзЗржХрж╢ржи)
# TCP 6379 тЖТ (Redis cache ржХрж╛ржирзЗржХрж╢ржи)

# ЁЯз▒ ржорж╛ржирзЗ ржПржЗржЯрж╛ use ржХрж░рж╛рж░ ржХрж╛рж░ржг:
# ЁЯФТ рж╕рж┐ржХрж┐ржЙрж░рж┐ржЯрж┐ ржмрж╛рзЬрж╛рзЯ тАФ
# ржпрж╛рждрзЗ Laravel app-ржПрж░ pod-ржП ржЕржирзНржп ржХрзЛржирзЛ random pod ржмрж╛ рж╕рж╛рж░рзНржнрж┐рж╕ ржврзБржХрждрзЗ ржирж╛ ржкрж╛рж░рзЗред
# ЁЯЪл Unwanted network access ржмржирзНржз ржХрж░рзЗ тАФ
# ржорж╛ржирзЗ рж╢рзБржзрзБржорж╛рждрзНрж░ ржкрзНрж░рзЯрзЛржЬржирзАрзЯ рж╕рж╛рж░рзНржнрж┐рж╕ (ржпрзЗржоржи MySQL, Redis)-ржПрж░ ржХрж╛ржирзЗржХрж╢ржиржЗ ржЕржирзБржорзЛржжржи ржХрж░рзЗред
# ЁЯзй Microservice isolation ржжрзЗрзЯ тАФ
# ржкрзНрж░рждрж┐ржЯрж╛ рж╕рж╛рж░рзНржнрж┐рж╕ ржЖрж▓рж╛ржжрж╛ржнрж╛ржмрзЗ ржЪрж▓рзЗ, ржХрж┐ржирзНрждрзБ рж╢рзБржзрзБ trusted рж╕рж╛рж░рзНржнрж┐рж╕ржЧрзБрж▓рж╛ ржкрж░рж╕рзНржкрж░рзЗрж░ рж╕рж╛ржерзЗ ржХржерж╛ ржмрж▓рзЗред