apiVersion: v1
kind: Service
metadata:
  name: agrobd-laravel-app
  namespace: agrobd-app
  labels:
    app: agrobd-laravel-app
spec:
  selector:
    app: agrobd-laravel-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: ClusterIP
